function test() {
    var t = document.getElementById('Gender');
    if (t.value=='woman'){
        document.getElementById('manto').style.display="block";
        document.getElementById('Man').style.display="none";
        document.getElementById('Woman').style.display="block";
        document.getElementById('T-shrt').style.display="none";
        document.getElementById('Pirhan').style.display="none";
        document.getElementById('Pants').style.display="none";
        document.getElementById('underDressman').style.display="none";
        document.getElementById('fallKoat').style.display="none";
        document.getElementById('paltoman').style.display="none";
        document.getElementById('jelighe').style.display="none";
        document.getElementById('koat').style.display="none";
        document.getElementById('zhakat').style.display="none";
        document.getElementById('hodi').style.display="none";
        document.getElementById('jin').style.display="none";
        document.getElementById('sox').style.display="none";
    }
    if (t.value=='man'){
        document.getElementById('Pirhan').style.display="block";
        document.getElementById('Man').style.display="block";
        document.getElementById('Woman').style.display="none";
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
}

function forwoman() {
    var w = document.getElementById('For-Woman');
    if (w.value=='manto'){
        document.getElementById('manto').style.display="block";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='shomiz'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="block";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='bloz'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="block";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='pants'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="block";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='Tshirt'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="block";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='tonic'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="block";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='sleep'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="block";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='skirt'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="block";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='kapshen'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="block";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='majlesi'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="block";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='fallKoat'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="block";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='uderDress'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="block";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='woSox'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="block";
        document.getElementById('womanZhakat').style.display="none";
    }
    if (w.value=='woZhakat'){
        document.getElementById('manto').style.display="none";
        document.getElementById('shomiz').style.display="none";
        document.getElementById('bloz').style.display="none";
        document.getElementById('womenpants').style.display="none";
        document.getElementById('womentTshert').style.display="none";
        document.getElementById('tonic').style.display="none";
        document.getElementById('sleep').style.display="none";
        document.getElementById('skirt').style.display="none";
        document.getElementById('kapshen').style.display="none";
        document.getElementById('majlesi').style.display="none";
        document.getElementById('womankoat').style.display="none";
        document.getElementById('underdreeswoman').style.display="none";
        document.getElementById('woSox').style.display="none";
        document.getElementById('womanZhakat').style.display="block";
    }
}